#Python Programs to demonstrate use of list and various functions of it
print("Program :- MSc CS & CL")
print("Semester-1")
print("Name : Komal Gupta")
print("Enrollment : 92600565010")
print("Practical-11")

list = [4,8,12,16,20,40]
list1 = [5,10,15,20,25]
print("Original values in list : ",list)
list.append(24)
print("Append function function in a list : ",list)
list.insert(8,28)
print("Add function in a list : ",list)
list.remove(28)
print("Remove function in a list : ",list)
list.pop()
print("Pop function in a list : ",list)
list.sort()
print("Sorted list : ",list)
print("Length of numbers : ",len(list))
print("Maximum number from a list : ",max(list))
print("Minimum number from a list : ",min(list))
print("Sum of values in a list : ",sum(list))
print("Count of 4 : ",list.count(4))
print("Index of 12 : ",list.index(12))
print("Values in list before extending : ",list1)
list.extend(list1)
print("Extended list : ",list)
list.reverse()
print("Reverse function is a list : ",list1)
